server:
  port: 8445

spring:
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    debug: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

