server:
  port: 8445

spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    springsecurity:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    debug: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

